### ISSUE TITLE
More file types?

### ISSUE THREAD

**Issue by MichaelMartinez** [AIxHunter/FileWizardAI#1]
Really cool project and thank you for sharing.

That said, it would be awesome to handle more file types. This is a list of file types OpenAI supports: https://platform.openai.com/docs/assistants/tools/file-search/supported-files

**Comment by AIxHunter** [comment]
Thank you for your feedback!

The file processing is actually handled on the backend by Llama-Index, only the file's content is sent to the API (such as the OpenAI API), not the file itself. This approach makes it independent of any specific API, while also reducing the amount of data sent to the API, lowering both costs and transmission time.

In addition, I'm currently working on adding support for more default file extensions, as well as allowing users to add their own custom extensions directly through the user interface.

**Comment by MichaelMartinez** [comment]
Awesome. I see that SimpleDirectoryReader already supports .csv , .docx, .epub, .hwp, .ipynb, .jpeg, .jpg, .mbox, .md, .mp3, .mp4, .pdf, .png, .ppt, .pptm, .pptx out of the box. Is there a technical reason why I can't just change: [frontend/src/app/app.component.ts](https://github.com/AIxHunter/FileWizardAI/blob/964216f1d5fbd1469e6cfdf997ebb9851bb23628/frontend/src/app/app.component.ts#L87) to accept more extensions?

**Comment by AIxHunter** [comment]
Yes exactly, however by adding new extensions the backend may fail, because llama index may not be able to treat them, so extra dependencies that can handle these extensions should be added.

**Comment by AIxHunter** [comment]
Issue fixed with the latest release [v0.2.0](https://github.com/AIxHunter/FileWizardAI/releases/tag/v0.2.0), users have the ability to add extensions through the UI.
I will close the issue, feel free to reopen if the problem persists.
