### ISSUE TITLE
[Feature] support using groq hosted llama-3.2-90b-vision-preview for both text and image organization

### ISSUE THREAD

**Issue by barakplasma** [AIxHunter/FileWizardAI#6]
I noticed on [groq vision docs](https://console.groq.com/docs/vision) / [groq playground](https://console.groq.com/playground?model=llama-3.2-90b-vision-preview) that they have the latest llama model which also supports images. Is there a way / plan to use this instead of ollama?

**Comment by AIxHunter** [comment]
Yes, actually Groq is the recommended model to be used (at least for text processing), you only need to update your **.env** file to point to Groq, check the examples section in the [documentation](https://github.com/AIxHunter/FileWizardAI/blob/main/.env.md#examples)

**Comment by barakplasma** [comment]
Thanks

**Comment by AIxHunter** [comment]
@barakplasma your welcome, if you tested newer models for Groq can you please create a PR and update the Groq models in the .env file in that documentation ?
